/** Independent two-year change map. Does not depend on runComparison or comparisonRows. */
(function(){
"use strict";
const OWNER="jwilsonschutter2",CACHE=new Map(),SRC="pc-independent-change",FILL="pc-independent-change-fill",LINE="pc-independent-change-line";
let map=null,exportData=null;
const el=id=>document.getElementById(id),digits=(v,n)=>{const m=String(v??"").match(/\d+/);return m?m[0].padStart(n,"0").slice(-n):"";};
const value=v=>{const n=Number(v);return Number.isFinite(n)&&n>-666666666?n:null;};
function status(text,kind){const n=el("changeMapStatus");n.textContent=text;n.className=`map-status ${kind||"muted"}`;}
function rowId(r,level){const base=digits(r.state,2)+digits(r.county,3)+digits(r.tract,6);return level==="blockgroup"?base+digits(r["block group"],1):base;}
function featureId(f,level){const p=f.properties||{},length=level==="blockgroup"?12:11;for(const k of ["GEOID","GEOID20","GEOID10","geoid","AFFGEOID"]){const s=String(p[k]??"").replace(/\D/g,"");if(s.length>=length)return s.slice(-length);}const base=digits(p.STATEFP??p.STATEFP20??p.STATEFP10,2)+digits(p.COUNTYFP??p.COUNTYFP20??p.COUNTYFP10,3)+digits(p.TRACTCE??p.TRACTCE20??p.TRACTCE10,6);return level==="blockgroup"?base+digits(p.BLKGRPCE??p.BLKGRPCE20??p.BLKGRPCE10,1):base;}
function boundaryUrl(year,level,state,county){const folder=level==="blockgroup"?"BG":"TRACT";const file=+year===2010?(level==="blockgroup"?`tl_2010_${state}_bg10.geojson.gz`:`tl_2010_${state}${county}_tract10.geojson.gz`):`tl_${year}_${state}_${level==="blockgroup"?"bg":"tract"}.geojson.gz`;return `https://raw.githubusercontent.com/${OWNER}/${year}Cenv1/main/${year}/${folder}/${file}`;}
async function decode(response){const b=new Uint8Array(await response.arrayBuffer());if(b[0]!==31||b[1]!==139)return JSON.parse(new TextDecoder().decode(b));if(typeof DecompressionStream!=="function")throw Error("This browser cannot decompress .gz boundaries.");return JSON.parse(await new Response(new Blob([b]).stream().pipeThrough(new DecompressionStream("gzip"))).text());}
async function boundary(year,level,state,county){const url=boundaryUrl(year,level,state,county);if(!CACHE.has(url)){const r=await fetch(url,{mode:"cors",cache:"force-cache"});if(!r.ok)throw Error(`Boundary request failed (${r.status}): ${url}`);CACHE.set(url,await decode(r));}const data=structuredClone(CACHE.get(url)),prefix=state+county;data.features=data.features.filter(f=>featureId(f,level).startsWith(prefix));return data;}
async function census(year,topic){const url=buildSingleTopicUrl(year,topic);if(!url)throw Error("Current dataset and geography selections are incomplete.");const r=await fetch(url);if(!r.ok)throw Error(`Census request for ${year} failed (${r.status}).`);return apiArrayToObjects(await r.json());}
function validate(data,rows,level,state,county,year){const length=level==="blockgroup"?12:11,prefix=state+county,ids=data.features.map(f=>featureId(f,level)),rowIds=rows.map(r=>rowId(r,level));const invalid=[...ids,...rowIds].filter(id=>id.length!==length||!id.startsWith(prefix));const dup=a=>a.filter((x,i)=>a.indexOf(x)!==i);if(invalid.length||dup(ids).length||dup(rowIds).length)throw Error(`${year} GEOID validation failed: ${invalid.length} invalid IDs, ${new Set(dup(ids)).size} duplicate boundaries, ${new Set(dup(rowIds)).size} duplicate API rows.`);}
function populate(){const select=el("changeMapVariable"),previous=select.value;select.innerHTML='<option value="">-- Select a variable --</option>';selectedTables.forEach(id=>{const o=document.createElement("option");o.value=id;o.textContent=tableFriendlyNames[id]?`${tableFriendlyNames[id]} (${id})`:id;select.append(o);});if(selectedTables.includes(previous))select.value=previous;else if(selectedTables.length===1)select.value=selectedTables[0];}
window.populateChangeMapVariables=populate;
function buildFeatures(oldGeo,newGeo,oldRows,newRows,topic,level){const oldValues=new Map(oldRows.map(r=>[rowId(r,level),value(r[topic])])),newValues=new Map(newRows.map(r=>[rowId(r,level),value(r[topic])]));let matched=0;newGeo.features.forEach((f,i)=>{const id=featureId(f,level),a=oldValues.get(id)??null,b=newValues.get(id)??null,d=a!=null&&b!=null?b-a:null,p=d!=null&&a!==0?d/a*100:null;if(a!=null&&b!=null)matched++;f.id=i;f.properties={...(f.properties||{}),__geoid:id,__earlier:a,__later:b,__difference:d,__percent:p,__method:a!=null?"direct GEOID":"unmatched"};});return{geojson:newGeo,matched,oldOnly:[...oldValues.keys()].filter(id=>!newValues.has(id)).length};}
function bounds(data){const b=new mapboxgl.LngLatBounds();function walk(c){if(!Array.isArray(c))return;if(c.length>=2&&Number.isFinite(c[0])&&Number.isFinite(c[1]))b.extend(c);else c.forEach(walk);}data.features.forEach(f=>f.geometry&&walk(f.geometry.coordinates));return b;}
function render(result,field,oldYear,newYear,topic,token){mapboxgl.accessToken=token;if(!map){map=new mapboxgl.Map({container:"prettyCensusChangeMap",style:"mapbox://styles/mapbox/light-v11",center:[-96,38],zoom:3});map.addControl(new mapboxgl.NavigationControl(),"top-right");}const draw=()=>{[LINE,FILL].forEach(id=>{if(map.getLayer(id))map.removeLayer(id);});if(map.getSource(SRC))map.removeSource(SRC);map.addSource(SRC,{type:"geojson",data:result.geojson,generateId:true});const vals=result.geojson.features.map(f=>Math.abs(value(f.properties[field])||0)).sort((a,b)=>a-b),limit=vals[Math.floor(vals.length*.95)]||1;map.addLayer({id:FILL,type:"fill",source:SRC,paint:{"fill-color":["case",["==",["get",field],null],"rgba(180,180,180,.25)",["interpolate",["linear"],["to-number",["get",field]],-limit,"#b2182b",0,"#f7f7f7",limit,"#2166ac"]],"fill-opacity":.82}});map.addLayer({id:LINE,type:"line",source:SRC,paint:{"line-color":"#fff","line-width":.6}});map.on("mousemove",FILL,e=>{const p=e.features[0].properties;el("changeMapReadout").innerHTML=`<strong>GEOID:</strong> ${escapeHtml(p.__geoid)}<br><strong>${oldYear}:</strong> ${p.__earlier==null?"No data":Number(p.__earlier).toLocaleString()}<br><strong>${newYear}:</strong> ${p.__later==null?"No data":Number(p.__later).toLocaleString()}<br><strong>Change:</strong> ${p[field]==null?"No data":Number(p[field]).toLocaleString(undefined,{maximumFractionDigits:2})}`;});const b=bounds(result.geojson);if(!b.isEmpty())map.fitBounds(b,{padding:30,duration:0});el("changeMapLegend").innerHTML=`<strong>${escapeHtml(tableFriendlyNames[topic]||topic)}</strong><div>Red: decrease</div><div>White: little change</div><div>Blue: increase</div>`;setTimeout(()=>map.resize(),0);};if(map.isStyleLoaded())draw();else map.once("style.load",draw);}
async function build(){const y1=+el("changeMapYear1").value,y2=+el("changeMapYear2").value,topic=el("changeMapVariable").value,metric=el("changeMapMetric").value,token=el("changeMapboxToken").value.trim()||el("mapboxToken").value.trim(),level=geoLevel,state=selectedState,county=selectedCounty;if(!y1||!y2||y1===y2||!topic||!token)return status("Choose two different years, a variable, and a Mapbox token.","error");if(!["tract","blockgroup"].includes(level)||!state||state==="*"||!county||county==="*")return status("Select one state, one county, and Tract or Block Group above.","error");const oldYear=Math.min(y1,y2),newYear=Math.max(y1,y2);try{status("Loading two independent Census requests and boundary vintages...","checking");const[og,ng,or,nr]=await Promise.all([boundary(oldYear,level,state,county),boundary(newYear,level,state,county),census(oldYear,topic),census(newYear,topic)]);validate(og,or,level,state,county,oldYear);validate(ng,nr,level,state,county,newYear);const result=buildFeatures(og,ng,or,nr,topic,level);exportData=result.geojson;render(result,metric,oldYear,newYear,topic,token);el("changeMapQa").textContent=`${result.matched} direct GEOID matches; ${result.oldOnly} earlier-year GEOIDs absent from the later year.`;el("exportChangeMapGeoJsonBtn").disabled=false;status(`Independent change map created on ${newYear} boundaries.`,"success");}catch(e){console.error(e);status(e.message||String(e),"error");}}
document.addEventListener("DOMContentLoaded",()=>{el("buildChangeMapBtn").addEventListener("click",build);el("exportChangeMapGeoJsonBtn").addEventListener("click",()=>{if(exportData)downloadGeoJson(exportData,`change_${el("changeMapYear1").value}_to_${el("changeMapYear2").value}_${geoLevel}_${selectedState}_${selectedCounty}.geojson`);});document.addEventListener("change",e=>{if(e.target.classList.contains("presetCheckbox")||e.target.id==="tableInput")populate();});});
})();
